# Generated by Django 3.2.2 on 2021-05-08 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '親会社モデル',
            },
        ),
        migrations.CreateModel(
            name='ChildCompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(error_messages={'unique': 'A user with that username already exists.  '}, help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, unique=True, verbose_name='会社名')),
                ('email', models.EmailField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('parent_company', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='TTimes.parentcompanymodel', verbose_name='親会社')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '子会社モデル',
                'verbose_name_plural': '子会社モデル',
            },
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('employee_number', models.IntegerField(default=None, verbose_name='社員番号')),
                ('authority', models.IntegerField(choices=[(0, '一般職'), (1, '管理職')], default=0, verbose_name='職位')),
                ('regular_start', models.TimeField(verbose_name='始業時間')),
                ('regular_finish', models.TimeField(verbose_name='終業時間')),
                ('day_break_start', models.TimeField(verbose_name='休憩開始時間')),
                ('day_break_finish', models.TimeField(verbose_name='休憩終了時間')),
                ('night_break_start', models.TimeField(verbose_name='(夜)休憩開始時間')),
                ('night_break_finish', models.TimeField(verbose_name='(夜)休憩終了時間')),
                ('ot_style', models.IntegerField(choices=[(0, '日当'), (1, '時給'), (2, '固定')], default=1, verbose_name='残業形態')),
                ('morning_style', models.IntegerField(choices=[(0, '日当'), (1, '時給'), (2, '固定')], default=1, verbose_name='早出形態')),
                ('night_style', models.IntegerField(choices=[(0, '日当'), (1, '時給'), (2, '固定')], default=2, verbose_name='夜勤形態')),
                ('holiday_style', models.IntegerField(choices=[(0, '日当'), (1, '時給'), (2, '固定')], default=0, verbose_name='休出形態')),
                ('ot_wage', models.IntegerField(default=None, verbose_name='残業単価')),
                ('morning_wage', models.IntegerField(default=None, verbose_name='早出単価')),
                ('night_wage', models.IntegerField(default=None, verbose_name='夜勤単価')),
                ('holiday_wage', models.IntegerField(default=None, verbose_name='休出単価')),
                ('rest_paid_holiday', models.IntegerField(default=None, verbose_name='残有休')),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='勤務先')),
            ],
            options={
                'verbose_name_plural': '従業員モデル',
            },
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_style', models.IntegerField(choices=[(0, '日勤'), (1, '夜勤')], default=0, verbose_name='日勤/夜勤')),
                ('in_out', models.IntegerField(choices=[(0, '出勤'), (1, '退勤')], verbose_name='出勤/退勤')),
                ('attendance_datetime', models.DateTimeField(verbose_name='打刻日時')),
                ('arrive_correct', models.TimeField(blank=True, null=True, verbose_name='(修正)出社時間')),
                ('leave_correct', models.TimeField(blank=True, null=True, verbose_name='(修正)退社時間')),
                ('correct_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='修正理由・備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='勤務先')),
                ('corrector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='修正者', to='TTimes.staffmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='TTimes.staffmodel')),
            ],
            options={
                'verbose_name_plural': '勤怠モデル',
            },
        ),
    ]
