# Generated by Django 3.1.7 on 2021-04-16 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('employee_number', models.IntegerField(default=None, verbose_name='社員番号')),
                ('authority', models.IntegerField(choices=[(0, '一般職'), (1, '管理職')], default=0, verbose_name='職位')),
                ('regular_start', models.TimeField(verbose_name='始業時間')),
                ('regular_finish', models.TimeField(verbose_name='終業時間')),
                ('day_break_start', models.TimeField(verbose_name='休憩開始時間')),
                ('day_break_finish', models.TimeField(verbose_name='休憩終了時間')),
                ('night_break_start', models.TimeField(verbose_name='(夜)休憩開始時間')),
                ('night_break_finish', models.TimeField(verbose_name='(夜)休憩終了時間')),
                ('ot_style', models.IntegerField(choices=[(0, '日当'), (1, '時給'), (2, '固定')], default=1, verbose_name='残業形態')),
                ('morning_style', models.IntegerField(choices=[(0, '日当'), (1, '時給'), (2, '固定')], default=1, verbose_name='早出形態')),
                ('night_style', models.IntegerField(choices=[(0, '日当'), (1, '時給'), (2, '固定')], default=2, verbose_name='夜勤形態')),
                ('holiday_style', models.IntegerField(choices=[(0, '日当'), (1, '時給'), (2, '固定')], default=0, verbose_name='休出形態')),
                ('ot_wage', models.IntegerField(default=None, verbose_name='残業単価')),
                ('morning_wage', models.IntegerField(default=None, verbose_name='早出単価')),
                ('night_wage', models.IntegerField(default=None, verbose_name='夜勤単価')),
                ('holiday_wage', models.IntegerField(default=None, verbose_name='休出単価')),
                ('rest_paid_holiday', models.IntegerField(default=None, verbose_name='残有休')),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TTimes.childcompanymodel', verbose_name='勤務先')),
            ],
        ),
        migrations.AddField(
            model_name='childcompanymodel',
            name='parent_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TTimes.parentcompanymodel', verbose_name='親会社'),
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_style', models.IntegerField(choices=[(0, '日勤'), (1, '夜勤')], default=0, verbose_name='日勤/夜勤')),
                ('in_out', models.IntegerField(choices=[(0, '出勤'), (1, '退勤')], default=None, verbose_name='出勤/退勤')),
                ('date', models.DateField(verbose_name='打刻日')),
                ('time', models.TimeField(verbose_name='打刻時間')),
                ('arrive_correct', models.TimeField(blank=True, null=True, verbose_name='(修正)出社時間')),
                ('leave_correct', models.TimeField(blank=True, null=True, verbose_name='(修正)退社時間')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTimes.childcompanymodel', verbose_name='勤務先')),
                ('corrector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrector', blank=True, null=True, to='TTimes.staffmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='TTimes.staffmodel')),
            ],
        ),
    ]
