# Generated by Django 3.1.7 on 2021-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='in_out',
            field=models.IntegerField(choices=[(0, '出勤'), (1, '退勤')], verbose_name='出勤/退勤'),
        ),
    ]
