# Generated by Django 3.2.4 on 2021-06-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTimes', '0002_rename_company_attendancemodel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcompanymodel',
            name='cut_off_day',
            field=models.IntegerField(default=20, verbose_name='締め日 0で月末'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=240, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='password',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='childcompanymodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parentcompanymodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
