# Generated by Django 3.1.7 on 2021-04-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTimes', '0002_auto_20210416_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemodel',
            options={'verbose_name_plural': '勤怠モデル'},
        ),
        migrations.AlterModelOptions(
            name='childcompanymodel',
            options={'verbose_name_plural': '子会社モデル'},
        ),
        migrations.AlterModelOptions(
            name='parentcompanymodel',
            options={'verbose_name_plural': '親会社モデル'},
        ),
        migrations.AlterModelOptions(
            name='staffmodel',
            options={'verbose_name_plural': '従業員モデル'},
        ),
    ]
