# Generated by Django 3.2.4 on 2021-06-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTimes', '0003_auto_20210611_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='password',
            field=models.CharField(max_length=50, verbose_name='メールアドレス'),
        ),
    ]
