# Generated by Django 3.2.4 on 2021-06-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TTimes', '0004_alter_staffmodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='arrive_correct',
        ),
        migrations.RemoveField(
            model_name='attendancemodel',
            name='leave_correct',
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='correct_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTimes.staffmodel'),
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='correct_time',
            field=models.TimeField(blank=True, null=True, verbose_name='(修正前)打刻日時'),
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='correction_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='修正承認日時'),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='corrector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='修正承認者', to='TTimes.staffmodel'),
        ),
    ]
